apiVersion: v1
kind: Service
metadata:
  name: nginx-blue-green-service
spec:
  type: NodePort
  selector:
    app: my-nginx
    color: blue  # Apunta al entorno azul por defecto
  ports:
    - port: 80
      targetPort: http
      nodePort: 30088  # Puerto expuesto en la EC2
